# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHwRgHdRvYojMMP077T3aPKZL0qPAGNJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

financing_schemas = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-04-21/financing_schemes.csv')
health_spending = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-04-21/health_spending.csv')
spending_purpose = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-04-21/spending_purpose.csv')

hf1 = financing_schemas[financing_schemas["indicator_code"] == "hf1_che"]
hf2 = financing_schemas[financing_schemas["indicator_code"] == "hf2_che"]
hf3 = financing_schemas[financing_schemas["indicator_code"] == "hf3_che"]
hf4 = financing_schemas[financing_schemas["indicator_code"] == "hf4_che"]
hfnec = financing_schemas[financing_schemas["indicator_code"] == "hfnec_che"]

financing_pct = pd.concat([hf1, hf2, hf3, hf4, hfnec]).copy()

ext_che = health_spending[health_spending["indicator_code"] == "ext_che"]
gghed_che = health_spending[health_spending["indicator_code"] == "gghed_che"]
pvtd_che = health_spending[health_spending["indicator_code"] == "pvtd_che"]

spending_pct = pd.concat([ext_che, gghed_che, pvtd_che]).copy()

che_usd2023 = health_spending[health_spending["indicator_code"] == "che_usd2023"]
ext_usd2023 = health_spending[health_spending["indicator_code"] == "ext_usd2023"]
gghed_usd2023 = health_spending[health_spending["indicator_code"] == "gghed_usd2023"]
pvtd_usd2023 = health_spending[health_spending["indicator_code"] == "pvtd_usd2023"]

spending_usd = pd.concat([
    che_usd2023,
    ext_usd2023,
    gghed_usd2023,
    pvtd_usd2023
]).copy()

hc1 = spending_purpose[spending_purpose["indicator_code"] == "hc1_che"]
hc2 = spending_purpose[spending_purpose["indicator_code"] == "hc2_che"]
hc3 = spending_purpose[spending_purpose["indicator_code"] == "hc3_che"]
hc4 = spending_purpose[spending_purpose["indicator_code"] == "hc4_che"]
hc5 = spending_purpose[spending_purpose["indicator_code"] == "hc5_che"]
hc6 = spending_purpose[spending_purpose["indicator_code"] == "hc6_che"]
hc7 = spending_purpose[spending_purpose["indicator_code"] == "hc7_che"]
hc9 = spending_purpose[spending_purpose["indicator_code"] == "hc9_che"]

purpose_pct = pd.concat([hc1, hc2, hc3, hc4, hc5, hc6, hc7, hc9]).copy()

latest_year = int(financing_pct["year"].max())
latest_purpose_year = int(purpose_pct["year"].max())

main_schemes = [
    "Government schemes and compulsory contributory health care financing schemes",
    "Household out-of-pocket payments (OOPS)",
    "Voluntary health care payment schemes",
]

government_data = financing_pct[
    financing_pct["financing_scheme"] ==
    "Government schemes and compulsory contributory health care financing schemes"
]

oop_data = financing_pct[
    financing_pct["financing_scheme"] ==
    "Household out-of-pocket payments (OOPS)"
]

voluntary_data = financing_pct[
    financing_pct["financing_scheme"] ==
    "Voluntary health care payment schemes"
]

trend_data = pd.concat([government_data, oop_data, voluntary_data])
trend_data = trend_data.groupby(["year", "financing_scheme"], as_index=False)["value"].median()

plt.figure(figsize=(10, 6))
for scheme in main_schemes:
    subset = trend_data[trend_data["financing_scheme"] == scheme]
    plt.plot(subset["year"], subset["value"], label=scheme)

plt.title("Analysis 1: Median Health Financing Mix Across Countries, 2000-2023")
plt.xlabel("Year")
plt.ylabel("Median share of current health expenditure (%)")
plt.legend()
plt.show()

government_2023 = financing_pct[
    (financing_pct["year"] == latest_year) &
    (
        financing_pct["financing_scheme"] ==
        "Government schemes and compulsory contributory health care financing schemes"
    )
]

oop_2023 = financing_pct[
    (financing_pct["year"] == latest_year) &
    (financing_pct["financing_scheme"] == "Household out-of-pocket payments (OOPS)")
]

voluntary_2023 = financing_pct[
    (financing_pct["year"] == latest_year) &
    (financing_pct["financing_scheme"] == "Voluntary health care payment schemes")
]

latest_financing = pd.concat([government_2023, oop_2023, voluntary_2023])

gov_oop = latest_financing.pivot_table(
    index="iso3_code",
    columns="financing_scheme",
    values="value"
)

gov_oop = gov_oop.dropna(subset=[
    "Government schemes and compulsory contributory health care financing schemes",
    "Household out-of-pocket payments (OOPS)"
])

x = gov_oop["Government schemes and compulsory contributory health care financing schemes"]
y = gov_oop["Household out-of-pocket payments (OOPS)"]

plt.figure(figsize=(8, 6))
plt.scatter(x, y)

z = np.polyfit(x, y, 1)
p = np.poly1d(z)
xp = np.linspace(x.min(), x.max(), 100)
plt.plot(xp, p(xp), color="red")

label_points = pd.concat([gov_oop.nlargest(3, y.name), gov_oop.nlargest(3, x.name)])
label_points = label_points[~label_points.index.duplicated(keep="first")]

for _, row in label_points.iterrows():
    plt.annotate(
        row.name,
        (
            row["Government schemes and compulsory contributory health care financing schemes"],
            row["Household out-of-pocket payments (OOPS)"]
        ),
        xytext=(5, 5),
        textcoords="offset points",
        fontsize=8
    )

plt.title("Analysis 2: Government vs Out-of-Pocket Spending in 2023")
plt.xlabel("Government share (%)")
plt.ylabel("Out-of-pocket share (%)")
plt.show()

print("Correlation:", round(x.corr(y), 3))

government_only = financing_pct[
    financing_pct["financing_scheme"] ==
    "Government schemes and compulsory contributory health care financing schemes"
]

gov_change = government_only.pivot_table(
    index="iso3_code",
    columns="year",
    values="value"
)

gov_change = gov_change[[2000, 2023]].dropna()
gov_change["change_pct_points"] = gov_change[2023] - gov_change[2000]
gov_change.columns.name = None

top_bottom = pd.concat([
    gov_change.nsmallest(10, "change_pct_points"),
    gov_change.nlargest(10, "change_pct_points")
]).sort_values("change_pct_points")

negative_change = top_bottom[top_bottom["change_pct_points"] < 0]
positive_change = top_bottom[top_bottom["change_pct_points"] >= 0]

plt.figure(figsize=(12, 8))
plt.barh(negative_change.index, negative_change["change_pct_points"], color="red")
plt.barh(positive_change.index, positive_change["change_pct_points"], color="skyblue")
plt.axvline(0, color="black")
plt.title("Analysis 3: Change in Government Financing Share, 2000 to 2023")
plt.xlabel("Percentage-point change")
plt.show()

gov_change = gov_change.sort_values("change_pct_points", ascending=False).reset_index()
gov_change.columns.name = None

gov_change.head(10)

total_spending = spending_usd[
    spending_usd["indicator_code"] == "che_usd2023"
]

spending_growth = total_spending.pivot_table(
    index="iso3_code",
    columns="year",
    values="value"
)

spending_growth = spending_growth[[2000, 2023]].dropna()
spending_growth["growth_pct"] = ((spending_growth[2023] / spending_growth[2000]) - 1) * 100

top_growth = spending_growth.nlargest(15, "growth_pct").sort_values("growth_pct")

plt.figure(figsize=(12, 8))
plt.barh(top_growth.index, top_growth["growth_pct"])
plt.title("Analysis 4: Largest Growth in Real Total Health Spending, 2000 to 2023")
plt.xlabel("Growth in constant 2023 US$ (%)")
plt.show()

spending_growth.sort_values("growth_pct", ascending=False).head(10)

external_financing = spending_pct[
    spending_pct["indicator_code"] == "ext_che"
]

external_2023 = external_financing[
    external_financing["year"] == latest_year
].copy()

top_external = external_2023.nlargest(15, "value").sort_values("value")

plt.figure(figsize=(12, 8))
plt.barh(top_external["iso3_code"], top_external["value"])
plt.title("Analysis 5: Countries Most Reliant on External Health Financing in 2023")
plt.xlabel("External share of current health expenditure (%)")
plt.show()

external_table = external_2023.sort_values("value", ascending=False)[
    ["country_name", "iso3_code", "year", "value"]
].copy()

external_table = external_table.rename(columns={
    "country_name": "country_name",
    "iso3_code": "iso3_code",
    "year": "year",
    "value": "external_health_financing_pct"
})

external_table.head(10)

purpose_2023 = purpose_pct[
    purpose_pct["year"] == latest_purpose_year
].copy()

purpose_medians = purpose_2023.groupby(
    "spending_purpose", as_index=False
)["value"].median().sort_values("value")

plt.figure(figsize=(12, 8))
plt.barh(purpose_medians["spending_purpose"], purpose_medians["value"])
plt.title("Analysis 6: Median Spending Purpose Shares in 2023")
plt.xlabel("Median share of current health expenditure (%)")
plt.show()

purpose_medians.sort_values("value", ascending=False)

print("Main conclusion:")
print("Countries with higher government financing tend to have lower out-of-pocket spending.")
print("Government funding is the dominant median financing source across countries.")
print("Curative care takes the largest median share of health spending purpose.")
print("Some countries remain highly dependent on external health financing.")